@extends('front.layouts.master')
@section('content')
    @include('front.components.slider')
    @include('front.components.about')
    @include('front.components.services')
    @include('front.components.testimonial')
    @include('front.components.process')
    @include('front.components.faq')
@endsection
